version: '3'

networks:
  app-network:


volumes:
  app-data:
  db-data:


services:

  webserver:
    image: nginx:1.23-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - .docker/nginx:/etc/nginx/conf.d
    networks:
      app-network:
    depends_on:
      - backend

  backend:
    build:
      context: .docker/php
    container_name: backend
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - .docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      app-network:
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - 3308:3306
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql/
      - .docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      app-network:
